FROM python:3.10-buster

WORKDIR /app

COPY src/requirements_webhook.txt requirements_webhook.txt

RUN pip install --no-cache-dir -r requirements_webhook.txt

COPY src/webhook_queue.py webhook_queue.py

COPY src/config.json src/config.json

ENV CELERY_BROKER_URL=amqp://broker:5672/

CMD ["celery", "-A", "webhook_queue", "worker", "--loglevel=info", "--concurrency=10"]