FROM python:3.10-buster

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean;

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64


WORKDIR /app


COPY jdbc/postgresql-42.7.3.jar jdbc/postgresql-42.7.3.jar 

COPY src /app/src


RUN pip install --no-cache-dir -r src/requirements_dash.txt

COPY dashboard.py .



CMD ["streamlit", "run", "dashboard.py"]