version: '3'
services:
  broker:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  psql:
    build: 
      context: .
      dockerfile: Dockerfile.psql
    ports:
      - '5432:5432'
  worker:
    build:
      context: .
      dockerfile: Dockerfile.queue
    image: worker
    depends_on:
      - broker
      - psql
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit//
      - PYTHONUNBUFFERED=1
  webhook:
    build: 
      context: .
      dockerfile: Dockerfile.webhook
    command: ["python", "webhook.py"]
    image: webhook
    ports:
      - '55555:55555'
    depends_on:
      - worker
      - broker
    environment:
      - PYTHONUNBUFFERED=1
  historico:
    build: 
      context: .
      dockerfile: ./Dockerfile.historico
    image: historico
    depends_on:
      - psql
  loja:
    build:
      context: .
      dockerfile: Dockerfile.loja
    image: loja
    depends_on:
      - psql
  web_gen:
    build:
      context: .
      dockerfile: Dockerfile.web_gen
    image: web_gen
    depends_on:
      - webhook
  dash:
    build: 
      context: .
      dockerfile: Dockerfile.dash
    image: dash
    ports:
      - '8050:8050'
    depends_on:
      - psql
      
