FROM python:3.10-buster

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean;

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64


WORKDIR /app

COPY src/requirements_pre_process.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY jdbc/postgresql-42.7.3.jar jdbc/postgresql-42.7.3.jar 

COPY src/config.json src/config.json
COPY src/pre_process_q2.py pre_process_q2.py

RUN mkdir json

CMD ["python", "pre_process_q2.py"]