FROM python:3.10-buster

WORKDIR /app

COPY mock/requirements_mock.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY mock/mock_utils.py mock_utils.py
COPY mock/txt_behaviour.py txt_behaviour.py


CMD ["python", "txt_behaviour.py"]